title: Ankit Gupta
logo: /assets/img/logo.jpg

description:
  <p align="left">
  <a href="https://www.linkedin.com/in/ankitgupta005/">LinkedIn</a>|
  <a href="https://therised.medium.com/">Medium</a>|
  <a href="https://github.com/guptankit005">GitHub</a>
  
  <br>   
  I'm a Data Scientist with experience in multiple industries and
  domains.
  <br>
  </p>


theme: jekyll-theme-minimal
